### ISSUE TITLE
Make the Add Client form be in same order as paper intake form

### ISSUE THREAD

**Issue by joeldenning** [JustUtahCoders/comunidades-unidas-internal#52]
See google doc intake form for the order

**Comment by MeghanBomberger** [comment]
Before diving into really changing around the fields wanted to run this by you all. Since the paper form doesn't cleanly follow sections and the goal is for quicker, cleaner data entry experience.

Since the paper form's structure doesn't match the current layout do we want to 
- combine the demographic and contact info sections into a single component and provide a straight shot data entry experience for their data entry people.
or
- have the component "breakpoints" be where the red lines are in the form to tie the user experience on the data entry end together

First option favors speed the second favors accuracy use wise. If their work environment has a lot of potential distractions (frequent interruptions, lots of noise, etc...) I'm leaning towards the second. However if their volume is high the first may be a better route and we can simple add the same red line breaks in the design to tie them visually.

**Comment by joeldenning** [comment]
Oops just saw this now -- we talked a bit in person about this, let me know if there's more here that still needs to be discussed.
